general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd = killall hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = on-battery && loginctl lock-session
}

listener {
    timeout = 330
    on-timeout = on-battery && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on-timeout = on-battery && systemctl suspend
}
